version: '3.6'
services:
  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@gavanlamb.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8000
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8000:8000
    networks:
      - infrastructure
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.gavanlamb.com`)
      traefik.http.routers.pgadmin.entrypoints: websecure
      traefik.http.routers.pgadmin.tls.certresolver: letsencrypt
      traefik.http.routers.pgadmin.service: pgadmin_svc
      traefik.http.services.pgadmin_svc.loadBalancer.server.port: 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/ || exit 1
      interval: 10s
      timeout: 9s
      retries: 10
      start_period: 60s

  postgres152:
    container_name: postgres152
    restart: unless-stopped
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PG152_PASSWORD}
      PGPORT: 8001
      PGDATA: /var/lib/postgresql/data
    networks:
      - infrastructure
    volumes:
      - postgres152:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --quiet --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER} || exit 1
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3

volumes:
  pgadmin:
    name: pgadmin
  postgres152:
    name: postgres152

networks:
  infrastructure:
    name: infrastructure
    external: true
