version: '3.9'
services:
  admin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - infrastructure
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@gavanlamb.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8000
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        traefik.enable: 'true'
        traefik.http.routers.pgadmin.rule: Host(`pgadmin.gavanlamb.com`)
        traefik.http.routers.pgadmin.entrypoints: websecure
        traefik.http.routers.pgadmin.tls.certresolver: letsencrypt
        traefik.http.routers.pgadmin.service: pgadmin
        traefik.http.services.pgadmin.loadBalancer.server.port: 8000
    logging:
      options:
        loki-external-labels: "job=-pgadmin"

  postgres152:
    image: postgres:15.2-alpine
    volumes:
      - postgres152:/var/lib/postgresql/data
    networks:
      - infrastructure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PG152_PASSWORD}
      PGPORT: 8001
      PGDATA: /var/lib/postgresql/data
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
    logging:
      options:
        loki-external-labels: "job=-postgres152"

  postgres152-exporter:
    image: prometheuscommunity/postgres-exporter
    networks:
      - infrastructure
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${PG152_PASSWORD}@postgres152:8001/shop?sslmode=disable"
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: postgres152
        prometheus.port: 9187
        prometheus.path: /metrics
    logging:
      options:
        loki-external-labels: "job=-postgres152-exporter"

volumes:
  pgadmin:
    name: pgadmin
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.19,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/share/docker/postgres/pgadmin"
  postgres152:
    name: postgres152
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.19,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/share/docker/postgres/postgres152"

networks:
  infrastructure:
    name: infrastructure
    external: true
